# Generated by Django 4.2.6 on 2023-10-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='create time'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='date_of_production',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cars',
            name='last_edit_time',
            field=models.DateTimeField(auto_now=True, verbose_name='last edit time'),
        ),
    ]
